export const GET_CONFIG = 'GET_CONFIG';
export const GET_MOVIE_GENRES = 'GET_MOVIE_GENRES';
export const GET_TV_GENRES = 'GET_TV_GENRES';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const CLEAR_MOVIE_DATA = 'CLEAR_MOVIE_DATA';
export const ERROR_FETCH_MOVIE = 'ERROR_FETCH_MOVIE';

export const GET_POPULAR_TV = 'GET_POPULAR_TV';
export const GET_TOP_RATED_TV = 'GET_TOP_RATED_TV';
export const GET_ON_THE_AIR_TV = 'GET_ON_THE_AIR_TV';
export const GET_ON_THE_AIR_TODAY_TV = 'GET_ON_THE_AIR_TODAY_TV';
export const GET_TV_DETAILS = 'GET_TV_DETAILS';
export const CLEAR_TV_DATA = 'CLEAR_TV_DATA';
export const ERROR_FETCH_TV = 'ERROR_FETCH_TV';

export const SEARCH_MOVIE_TV = 'SEARCH_MOVIE_TV';
export const SEARCH_ERROR =  'SEARCH_ERROR';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const GET_TRENDING = 'GET_TRENDING';

export const ERROR = 'ERROR';