export const GET_CONFIG = 'GET_CONFIG';
export const GET_MOVIE_GENRES = 'GET_MOVIE_GENRES';
export const GET_TV_GENRES = 'GET_TV_GENRES';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';

export const GET_POPULAR_TV = 'GET_POPULAR_TV';
export const GET_TOP_RATED_TV = 'GET_TOP_RATED_TV';

export const GET_TRENDING = 'GET_TRENDING';

export const ERROR = 'ERROR';